### PR TITLE
Update eventmesh-store-quickstart.zh-CN.md

### PR DESCRIPTION
**Pull request by TrumanDu**

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@TrumanDu  can you please add another lonely file for defibus instructions?

**Comment by TrumanDu** [comment]
@qqeasonchen sorry, i don't know about defibus . I just change the format

**Comment by qqeasonchen** [comment]
@TrumanDu The doc was updated already, you can join our wechat group if you want to contribue, welcome to join our community.

**Comment by qqeasonchen** [comment]
@TrumanDu can you let me know who you are through wecaht or email and discuss what you can contribute if you want?

**Pull request closed without merging**
